'use client'

import { FileDown } from 'lucide-react'
import { ReportAnalyticsChart } from '@/components/report-analytics-chart'

type Report = { agent: string; status: string; answer: string; model?: string; latency_ms?: number }
type EvidenceState = { status: string; decision: string; coverage: number; consistency: number; citation_completeness: number; rationale: string } | null

export function ReportWorkspace({ reports, evidenceState, answer }: { reports: Report[]; evidenceState: EvidenceState; answer: string | null }) {
  function download() { const blob = new Blob([answer ?? 'No report generated yet.'], { type: 'text/plain' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'docutrust-agent-report.txt'; link.click(); URL.revokeObjectURL(url) }
  return <div className="flex flex-col gap-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono text-xs uppercase tracking-[.18em] text-teal-700">Generated report</p><h2 className="mt-2 text-2xl font-semibold">How the answer was formed</h2><p className="mt-2 text-sm text-muted-foreground">A transparent summary of every agent, evidence check, and final decision.</p></div><button onClick={download} className="flex items-center gap-2 rounded-lg border bg-card px-3 py-2 text-sm font-semibold hover:bg-muted"><FileDown className="size-4" />Download report</button></div><section className="rounded-xl border bg-card p-5"><h3 className="font-semibold">Final report</h3><p className="mt-3 whitespace-pre-wrap text-sm leading-7">{answer ?? 'Run an analysis from Overview to generate a report.'}</p></section><ReportAnalyticsChart reports={reports} evidenceState={evidenceState} /><section className="grid gap-4 md:grid-cols-2">{reports.length ? reports.map((report) => <article key={`${report.agent}-${report.model}`} className="rounded-xl border bg-card p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold capitalize">{report.agent} agent</h3><span className="text-xs text-muted-foreground">{report.status}</span></div><p className="mt-2 text-sm leading-6 text-muted-foreground">{report.answer}</p><p className="mt-3 font-mono text-[10px] text-muted-foreground">{report.model ?? 'provider fallback'} · {report.latency_ms ?? 0}ms</p></article>) : <div className="rounded-xl border bg-card p-5 text-sm text-muted-foreground md:col-span-2">No agent findings yet. Start an analysis to populate this report.</div>}</section>{evidenceState && <section className="rounded-xl border bg-card p-5"><h3 className="font-semibold">Evidence decision</h3><div className="mt-3 grid gap-3 text-sm sm:grid-cols-3"><p>Coverage <strong>{Math.round(evidenceState.coverage * 100)}%</strong></p><p>Consistency <strong>{Math.round(evidenceState.consistency * 100)}%</strong></p><p>Citations <strong>{Math.round(evidenceState.citation_completeness * 100)}%</strong></p></div><p className="mt-3 text-sm text-muted-foreground">{evidenceState.rationale} Decision: <strong>{evidenceState.decision}</strong>.</p></section>}</div>
}
